// Rampart Riot — image & sprite-atlas loading
// Atlas JSON (generated by tools/art): { scale, pages:[png], frames:{name:[page,x,y,w,h,ox,oy,(frameScale)]}, anims:{name:{f:[names], fps, loop, ev}} }

class AssetStore {
  constructor() {
    this.images = new Map();
    this.atlases = new Map();
    this.frames = new Map();
    this.anims = new Map();
    this.json = new Map();
  }

  loadImage(url) {
    if (this.images.has(url)) return Promise.resolve(this.images.get(url));
    return new Promise((res) => {
      const img = new Image();
      img.decoding = 'async';
      img.onload = () => {
        const done = () => { this.images.set(url, img); res(img); };
        if (img.decode) img.decode().then(done, done); else done();
      };
      img.onerror = () => { console.warn('image failed', url); res(null); };
      img.src = url;
    });
  }
  img(url) { return this.images.get(url) || null; }

  // WebP atlas pages are ~3x smaller than PNG; use them when the browser can decode lossy WebP with alpha
  detectWebp() {
    if (this._webp) return this._webp;
    this._webp = new Promise(res => {
      const im = new Image();
      im.onload = () => res(this.webp = im.width === 1);
      im.onerror = () => res(this.webp = false);
      im.src = 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4WAoAAAAQAAAAAAAAAAAAQUxQSAwAAAARBxAR/Q9ERP8DAABWUDggGAAAABQBAJ0BKgEAAQAAAP4AAA3AAP7mtQAAAA==';
    });
    return this._webp;
  }

  async loadJSON(url) {
    if (this.json.has(url)) return this.json.get(url);
    const j = await fetch(url).then(r => r.json());
    this.json.set(url, j);
    return j;
  }

  async loadAtlas(name, base = 'assets/sprites/') {
    if (this.atlases.has(name)) return this.atlases.get(name);
    let data;
    try { data = await this.loadJSON(base + name + '.json'); }
    catch (e) { console.warn('atlas json failed', name, e); return null; }
    await this.detectWebp();
    const pages = await Promise.all(data.pages.map(async p => {
      if (this.webp) { const w = await this.loadImage(base + p.replace(/\.png$/, '.webp')); if (w) return w; }
      return this.loadImage(base + p);
    }));
    const inv = 1 / (data.scale || 1);
    const atlas = { name, scale: data.scale || 1, pages, frameNames: [] };
    for (const [fname, f] of Object.entries(data.frames)) {
      const img = pages[f[0]];
      if (!img) continue;
      this.frames.set(fname, { img, x: f[1], y: f[2], w: f[3], h: f[4], ox: f[5], oy: f[6], s: f[7] ? 1 / f[7] : inv });
      atlas.frameNames.push(fname);
    }
    for (const [aname, a] of Object.entries(data.anims || {})) {
      const frames = a.f.map(n => this.frames.get(n)).filter(Boolean);
      if (!frames.length) continue;
      this.anims.set(aname, { frames, fps: a.fps || 12, loop: a.loop !== false, dur: frames.length / (a.fps || 12), ev: a.ev || null });
    }
    this.atlases.set(name, atlas);
    return atlas;
  }

  unloadAtlas(name) {
    const a = this.atlases.get(name);
    if (!a) return;
    for (const f of a.frameNames) this.frames.delete(f);
    for (const k of [...this.anims.keys()]) { const an = this.anims.get(k); if (an.frames[0] && a.pages.includes(an.frames[0].img)) this.anims.delete(k); }
    this.atlases.delete(name);
  }

  frame(name) { return this.frames.get(name) || null; }
  anim(name) { return this.anims.get(name) || null; }
  hasAnim(name) { return this.anims.has(name); }

  // frame for animation at time t (seconds)
  animFrame(name, t) {
    const a = this.anims.get(name);
    if (!a) return null;
    const n = a.frames.length;
    let i = Math.floor(t * a.fps);
    i = a.loop ? ((i % n) + n) % n : Math.min(n - 1, Math.max(0, i));
    return a.frames[i];
  }
}

export const Assets = new AssetStore();

// Draw a frame with its anchor at (x, y) in the current transform's units.
export function drawFrame(ctx, f, x, y, flip = false, scale = 1) {
  if (!f) return;
  const s = f.s * scale;
  if (flip) {
    ctx.save();
    ctx.translate(x, y);
    ctx.scale(-1, 1);
    ctx.drawImage(f.img, f.x, f.y, f.w, f.h, -f.ox * s, -f.oy * s, f.w * s, f.h * s);
    ctx.restore();
  } else {
    ctx.drawImage(f.img, f.x, f.y, f.w, f.h, x - f.ox * s, y - f.oy * s, f.w * s, f.h * s);
  }
}

// Draw a frame scaled to fit a box (for icons / portraits), centered.
export function drawFrameFit(ctx, f, cx, cy, size, alpha = 1) {
  if (!f) return;
  const k = size / Math.max(f.w, f.h);
  if (alpha !== 1) { ctx.save(); ctx.globalAlpha *= alpha; }
  ctx.drawImage(f.img, f.x, f.y, f.w, f.h, cx - (f.w * k) / 2, cy - (f.h * k) / 2, f.w * k, f.h * k);
  if (alpha !== 1) ctx.restore();
}
