// Rampart Riot — bundled font loading (subset fonts generated by tools/fonts/subset.py)
const FONTS = [
  ['RRSans', 'assets/fonts/rr-sans-bold.woff', { weight: '700' }],
  ['RRSans', 'assets/fonts/rr-sans-black.woff', { weight: '900' }],
  ['RRSerif', 'assets/fonts/rr-serif.woff', { weight: '600' }],
  ['RRDisplay', 'assets/fonts/rr-display.woff', { weight: '900' }],
];
export async function loadFonts() {
  if (!('FontFace' in window)) return;
  await Promise.all(FONTS.map(async ([fam, url, desc]) => {
    try {
      const ff = new FontFace(fam, `url(${url})`, desc);
      await ff.load();
      document.fonts.add(ff);
    } catch (e) { /* fall back to system fonts */ }
  }));
}
